### ISSUE TITLE
Ukulib not showing up in ModMenu

### ISSUE THREAD

**Issue by gxjakkap** [uku3lig/ukulib#18]
I'm currently running Fabric 1.20.6, fabric-api 0.97.8+1.20.6, ukulib 1.2.0+1.20.6, modmenu 10.0.0-beta.1, betterhurtcam 1.8.0+mc1.20.6 and there's this error log while launching.

https://0bin.net/paste/gTFbgkN3#8rY3tu3Mnm+e-5C4OML02sTGexyyq/5zkGfM4Mzl8E5

The config button in options worked fine, but it would be nice to have config in ModMenu.

**Comment by uku3lig** [comment]
fixed in aa0a3fc05b694ce75c305e6fd5602c82be57976e

thanks for reporting!
