### ISSUE TITLE
Problems with Better Hurt Cam

### ISSUE THREAD

**Issue by sashaironfist** [uku3lig/ukulib#3]
so when I try to use BetterHurtCam version 1.5.2 it says I need ukulib version 0.6.1+1.18.2. When I try to launch them together if I try to go into controls (in Minecraft) on release fabric-loader-0.14.11-1.19. It keeps saying saving world and then crashes, but I wasn't in a world???

**Comment by uku3lig** [comment]
you're using ukulib for 1.18.2 while being on minecraft 1.19...
