### ISSUE TITLE
Problems with Better Hurt Cam Part 2

### ISSUE THREAD

**Issue by sashaironfist** [uku3lig/ukulib#4]
I tried ukulib for 1.19 still crashes and says "Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'ukulib' (ukulib) 0.2.1+1.19 with version 0.3.0 or later.
Unmet dependency listing:
	 - Mod 'BetterHurtCam' (betterhurtcam) 1.5.2 requires version 0.3.0 or later of mod 'ukulib' (ukulib), but only the wrong version is present: 0.2.1+1.19!
	 - Mod 'BetterHurtCam+mc1.14' (betterhurtcam-mc114) 1.5.2 requires any 1.14.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19!
	 - Mod 'BetterHurtCam+mc1.15' (betterhurtcam-mc115) 1.5.2 requires any 1.15.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19!
	 - Mod 'BetterHurtCam+mc1.16' (betterhurtcam-mc116) 1.5.2 requires any 1.16.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19!
	 - Mod 'BetterHurtCam+mc1.17' (betterhurtcam-mc117) 1.5.2 requires any 1.17.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19!
	 - Mod 'BetterHurtCam+mc1.18' (betterhurtcam-mc118) 1.5.2 requires any 1.18.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19!
	 - Mod 'BetterHurtCam+mc1.19.3' (betterhurtcam-mc1193) 1.5.2 requires any version after 1.19.2 of 'Minecraft' (minecraft), but only the wrong version is present: 1.19!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
"

**Comment by uku3lig** [comment]
1.19 isn't really supported anymore, you can either try your luck with the 1.19.2 builds of ukulib or simply update your instance to minecraft 1.19.2 or 1.19.3

**Comment by sashaironfist** [comment]
its just I am good at pvp and the server is on 1.19, best server its whitelisted though

**Comment by uku3lig** [comment]
use multiconnect, https://modrinth.com/mod/multiconnect

**Comment by sashaironfist** [comment]
k

**Comment by sashaironfist** [comment]
have any ideas for hardcore worlds?

**Comment by uku3lig** [comment]
what do you mean by that?

**Comment by uku3lig** [comment]
what? multiconnect is used to connect to older servers, singleplayer world conversion is already handled by the vanilla game

**Comment by sashaironfist** [comment]
yeah but i'm scared if I redo my hardcore world its gonna break

**Comment by uku3lig** [comment]
well first of all, if you go from 1.19 to 1.19.2/3, the risk of anything breaking is so small that it shouldn't even be considered. and second, make a backup of your world before loading it in the new version

**Comment by sashaironfist** [comment]
thanks i will try that

**Comment by sashaironfist** [comment]
https://pastebin.com/EG7abCp3

**Comment by uku3lig** [comment]
you downloaded ukulib for 1.18.2...

**Comment by sashaironfist** [comment]
ok

**Comment by sashaironfist** [comment]
it worked, thanks for the help. and about the "you downloaded ukulib for 1.18.2..." part I was just using the version it said. Bye

**Comment by sashaironfist** [comment]
Bye and thanks for the help
