### ISSUE TITLE
A option to disable button from options screen and integrate with Mod Menu

### ISSUE THREAD

**Issue by xttlegendgithub** [uku3lig/ukulib#6]
Please make the settings menu accessible from the Mod Menu and make a option to disable the button in the Minecraft options screen.
This is very needed because if more mods would do this, your options screen would be a mess

**Comment by uku3lig** [comment]
automatic modmenu integration is already implemented in the 1.0 branch, which should hopefully release soon

**Comment by xttlegendgithub** [comment]
Thanks for your quick response. Okay, but a option to disable the button in the Minecraft option's screen would still be great!

**Comment by uku3lig** [comment]
Added in bae27d4
