### ISSUE TITLE
uklib 1.0.0 beta + totem counter 

### ISSUE THREAD

**Issue by e-lunev** [uku3lig/ukulib#9]
When I installed totem counter I got an error that I need ukulib library version 1.0.0 +, but when I download any version of 1.0.0 beta and the latest version of totem counter, I have game crashes

https://pastebin.com/kmLJH3Dv

**Comment by uku3lig** [comment]
the current stable release of totemcounter only works with ukulib 0.7.0, and if you want to use betterhurtcam use version 1.5.5, not 1.6.0
